##############################################################################
# Automations to display the weather forecast and current temp on page 2

automation:
  # Display weather details on page 2 when weather updates or on HASP init
  - alias: hasp_plate01_p2_Weather
    trigger:
    - platform: state
      entity_id: sensor.weather_temperature
    - platform: mqtt
      topic: 'hasp/plate01/status'
      payload: 'ON'
    action:
    - service: script.hasp_plate01_update_message
      data:
        objectId: 'p[2].b[6]'
        text: '"{{states.sensor.weather_temperature.state}}F"'
    - service: script.hasp_plate01_update_message
      data:
        objectId: 'p[2].b[7]'
        text: '"{{states.sensor.weather_current.state|wordwrap(20, wrapstring="\\r")}}"'
