homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.7864
  longitude: -85.5506
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Sensors for weather and media player information
sensor:
  - platform: yweather
    name: Weather
    monitored_conditions:
      - weather_current
      - temperature
      - temp_min
      - temp_max
      - humidity
  - platform: template
    sensors:
      media_player_title:
        value_template: '{{ states.media_player.media_player.attributes.media_title }}'
      media_player_artist:
        value_template: '{{ states.media_player.media_player.attributes.media_artist }}'
      media_player_volume:
        value_template: '{{ states.media_player.media_player.attributes.volume_level }}'
# - platform: octoprint
  # name: OctoPrint
  # monitored_conditions:
    # - Current State
    # - Temperatures
    # - Job Percentage

# octoprint:
  # host: octoprint.local
  # api_key: YOUROCTOPRINTAPIKEY

media_player:
  - platform: gpmdp
    name: "Media Player"
    host: 127.0.0.1

alarm_control_panel:
  - platform: manual
    code: 1234

##############################################################################
# The input_text and input_number devices created below are essential to the
# page control automations and you'll probably want to carry them over to your
# own configuration
input_text:
  haswitchplate_pagebutton1_label:
    name: HASP Page Button 1 Label
    icon: mdi:book-open-page-variant
  haswitchplate_pagebutton2_label:
    name: HASP Page Button 2 Label
    icon: mdi:book-open-page-variant
  haswitchplate_pagebutton3_label:
    name: HASP Page Button 3 Label
    icon: mdi:book-open-page-variant

input_number:
  haswitchplate_pagebutton1_page:
    name: HASP Page Button 1 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  haswitchplate_pagebutton2_page:
    name: HASP Page Button 2 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  haswitchplate_pagebutton3_page:
    name: HASP Page Button 3 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  haswitchplate_active_page:
    name: HASP Active Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  haswitchplate_alarmcode1:
    name: AlarmCode1
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  haswitchplate_alarmcode2:
    name: AlarmCode2
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  haswitchplate_alarmcode3:
    name: AlarmCode3
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  haswitchplate_alarmcode4:
    name: AlarmCode4
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1

# Enable MQTT discovery: https://www.home-assistant.io/docs/mqtt/discovery/
# This is essential for HASP to create the required devices
mqtt:
  discovery:

group: !include groups.yaml
script: !include scripts.yaml

automation: !include_dir_merge_list automations/
scene: !include_dir_merge_list scenes/