# This set of automations require the OctoPrint component to be configured against
# a running OctoPrint installation and will fail without it.
# https://home-assistant.io/components/octoprint/
- alias: HASwitchPlate_3DPrinter_Init
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[5].font'
      payload: '1'
      retain: true
 
- alias: HASwitchPlate_3DPrinter_Printing
  trigger:
  - platform: template
    value_template: "{% if is_state('sensor.octoprint_current_state', 'Printing') %}true{% endif %}"
  - platform: state
    entity_id: sensor.octoprint_job_percentage    
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].bco'
      payload: '5285'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].pco'
      payload: '65535'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].font'
      payload: '1'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].txt'
      payload_template: '"Status:Printing\rProgress:{{(states.sensor.octoprint_job_percentage.state)|default(0)|round(1)}}%"'

- alias: HASwitchPlate_3DPrinter_Operational
  trigger:
  - platform: template
    value_template: "{% if is_state('sensor.octoprint_current_state', 'Operational') %}true{% endif %}"
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].bco'
      payload: '65535'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].pco'
      payload: '5285'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].font'
      payload: '2'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].txt'
      payload_template: '"Online"'

- alias: HASwitchPlate_3DPrinter_Paused
  trigger:
    platform: template
    value_template: "{% if is_state('sensor.octoprint_current_state', 'Paused') %}true{% endif %}"
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].bco'
      payload: '65535'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].pco'
      payload: '63488'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].font'
      payload: '2'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[4].txt'
      payload_template: '"Paused"'

# Show the head and bed temps.  My locale is set for deg F, and I want deg C, so
# the values are being converted in the template code
- alias: HASwitchPlate_3DPrinter_TempText
  trigger:
  - platform: state
    entity_id: sensor.octoprint_actual_tool0_temp
  - platform: state
    entity_id: sensor.octoprint_target_tool0_temp
  - platform: state
    entity_id: sensor.octoprint_actual_bed_temp
  - platform: state
    entity_id: sensor.octoprint_target_bed_temp
  condition:
  - condition: state
    entity_id: 'binary_sensor.haswitchplate'
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[9].b[5].txt'
      payload_template: '"Head: {{((states.sensor.octoprint_actual_tool0_temp.state|float-32)*(5/9))|round(1)}}/{{((states.sensor.octoprint_target_tool0_temp.state|float-32)*(5/9))|int}}\r Bed: {{((states.sensor.octoprint_actual_bed_temp.state|float-32)*(5/9))|round(1)}}/{{((states.sensor.octoprint_target_bed_temp.state|float-32)*(5/9))|int}}"'

# Every 30 seconds (default octoprint polling interval in Hass), add one pixel to the graph.      
# The graph on page 9 has 4 divisions, so we're calling the origin (y=0 in the graph) 50deg C and the top line 250deg C
# each pixel is one data point, the object on the page is 133 points tall
# my Location is using deg F, so I need to convert from F to C then map 50-250 into a range of 1-133
# 50C = 122F, 250C = 482.  So the range of values in our chart will be 482-122 = 360 degF
# 133/360 ~= 0.3694, so we can map our value in F to a 133-point-tall graph that goes from 50-250C with the formula: (degF - 122) * 0.3694
- alias: HASwitchPlate_3DPrinter_TempGraph
  trigger:
    platform: time
    seconds: '/30'
  condition:
  - condition: template
    value_template: "{% if is_state('sensor.octoprint_current_state', 'Printing') or is_state('sensor.octoprint_current_state', 'Operational') or is_state('sensor.octoprint_current_state', 'Paused') %}true{% endif %}"
  - condition: state
    entity_id: 'input_number.haswitchplate_active_page'
    state: '9.0'
  - condition: state
    entity_id: 'binary_sensor.haswitchplate'
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command'
      payload_template: "add 6,0,{{((states.sensor.octoprint_actual_tool0_temp.state|int-122)*0.3694)|int}}"
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command'
      payload_template: "add 6,1,{{((states.sensor.octoprint_actual_bed_temp.state|int-122)*0.3694)|int}}"