- alias: HASwitchPlate_Page10_Media
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b6.font'
      payload: '4'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b7.font'
      payload: '4'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b8.font'
      payload: '4'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b9.font'
      payload: '4'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b10.font'
      payload: '4'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b11.font'
      payload: '4'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b6.txt'
      payload: '"9"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b7.txt'
      payload: '";"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b8.txt'
      payload: '":"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b9.txt'
      payload: '"4"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b10.txt'
      payload: '"5"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p8.b11.txt'
      payload: '"6"'


