- alias: HASwitchPlate_Dimmers_Init
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[4].txt'
      payload: '"Light 1"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[5].txt'
      payload: '"Light 2"'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[6].txt'
      payload: '"Light 3"'

- alias: HASwitchPlate_p[4]b[7]_DimmerSliderUpdateHass
  trigger:
  - platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[4].b[7].val'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.light_1
      brightness: '{{ trigger.payload }}'

- alias: HASwitchPlate_p[4]b[7]_DimmerSliderUpdateHASP
  trigger:
  - platform: state
    entity_id: light.light_1
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[7].val'
      payload_template: '{{states.light.light_1.attributes.brightness|default(0)|int}}'

- alias: HASwitchPlate_p[4]b[8]_DimmerSliderUpdateHass
  trigger:
  - platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[4].b[8].val'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.light_2
      brightness: '{{ trigger.payload }}'

- alias: HASwitchPlate_p[4]b[8]_DimmerSliderUpdateHASP
  trigger:
  - platform: state
    entity_id: light.light_2
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[8].val'
      payload_template: '{{states.light.light_2.attributes.brightness|default(0)|int}}'

- alias: HASwitchPlate_p[4]b[9]_DimmerSliderUpdateHass
  trigger:
  - platform: mqtt
    topic: 'homeassistant/haswitchplate/HASwitchPlate/state/p[4].b[9].val'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.light_3
      brightness: '{{ trigger.payload }}'

- alias: HASwitchPlate_p[4]b[9]_DimmerSliderUpdateHASP
  trigger:
  - platform: state
    entity_id: light.light_3
  action:
  - service: mqtt.publish
    data_template:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[4].b[9].val'
      payload_template: '{{states.light.light_3.attributes.brightness|default(0)|int}}'

