- alias: HASwitchPlate_Weather
  trigger:
  - platform: state
    entity_id: sensor.weather_temperature
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[6].txt'
      payload_template: "\"{{states.sensor.weather_temperature.state}}F\""
      retain: true
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/command/p[2].b[7].txt'
      payload_template: "\"{{states.sensor.weather_current.state}}\""
      retain: true
