- alias: HASwitchPlate_Page2_Status
  trigger:
  - platform: mqtt
    topic: 'homeassistant/binary_sensor/HASwitchPlate/state'
    payload: 'ON'
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p2.b4.font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p2.b5.font'
      payload: '1'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p2.b6.font'
      payload: '3'
  - service: mqtt.publish
    data:
      topic: 'homeassistant/haswitchplate/HASwitchPlate/nextionattr/p2.b7.font'
      payload: '1'


